spring.application.name=coin
app.key=IoQaUSKsEAv6fYNsAVNCkOtd5eU3n7Lk0dxQ3MKLYJhsSruVLiLMSL1tZa6QKPNl
app.secret=Max41VlXUeWx7kkIrE7hzLEz2B7wKJAa3jBc2pHDGm2zbUHHnXCeIyglMMNYbScs
app.privatePass=admin123

